# Image de base
FROM node:18.20.2 

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install 

# Copier le reste des fichiers de l'application 
COPY . .

# Exposer le port que votre application utilise 
EXPOSE 3000

# Démarrer l'application
CMD ["node", "app.js"]